# Generated by Django 4.1.7 on 2024-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='', max_length=64, verbose_name='Профессия'),
        ),
    ]
