# Generated by Django 4.1.7 on 2023-02-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('STUDENT', 'Магистрант'), ('ADMIN', 'Педагог')], default='Магистрант', max_length=64, verbose_name='Позиция'),
        ),
    ]
