# Generated by Django 4.1.7 on 2024-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('START', 'На старте'), ('PROCESS', 'В процессе'), ('FINISH', 'Завершено')], default='На старте', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'В процессе'), ('FINISH', 'Завершено')], default='В процессе', max_length=64, verbose_name='Статус'),
        ),
    ]
