# Generated by Django 4.1.7 on 2024-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='#n ...', max_length=255, verbose_name='Название задачи'),
        ),
    ]
