# Generated by Django 4.1.7 on 2024-06-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='title',
        ),
    ]
