# Generated by Django 4.1.7 on 2023-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekend',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Открыто'),
        ),
    ]
